### ISSUE TITLE
Can I use the machine learning model for DNAscope when running TNscope?

### ISSUE THREAD

**Issue by G2GreenTea** [Sentieon/sentieon-models#2]
I haven't found the machine learning model for TNscope. So I wonder if I can use the machine learning model for DNAscope when running TNscope.

**Comment by DonFreed** [comment]
The models are specific for their particular algo, so DNAscope models need to be used with `--algo DNAscope` and TNscope models need to be used with `--algo TNscope`.

You can email support@sentieon.com for the latest version of the TNscope model.

By the way, Sentieon has some general recommendations for somatic variant calling in their somatic variant calling application note, https://support.sentieon.com/appnotes/somatic/
