### ISSUE TITLE
Which DNAscope model should be used for RNA-seq analysis?

### ISSUE THREAD

**Issue by G2GreenTea** [Sentieon/sentieon-models#3]
When I call SNV and InDel for RNA-seq data, which DNAscope model should be used, whole exome or whole genome?

**Comment by DonFreed** [comment]
You might try using DNAscope without a trained model file when calling variants from RNAseq data. You should also use the `--trim_soft_clip` argument to trim overhanging soft-clips.

I would not suggest using either the whole exome or whole genome models, as their training sets do not include RNAseq data.

**Comment by G2GreenTea** [comment]
Okay, I understand. Thank you for your prompt response.
