### ISSUE TITLE
Issue with DNAscope wes-interval.sh

### ISSUE THREAD

**Issue by gianfilippo** [Sentieon/sentieon-models#5]
Hi,

I am running your example pipeline "wes-interval.sh"

I am getting the following error

[E::main_mem] unknown read type '/home/sentieon-genomics-202112.07/models/DNAscopeIlluminaWES2.0.bundle/bwa.model'

This comes from the line
$SENTIEON_INSTALL_DIR/bin/sentieon bwa mem -R "@RG\tID:$RGID\tSM:$SM\tPL:$PL" -t $NT -K 10000000 -x $DNASCOPE_MODEL/bwa.model  $FASTA $FASTQ_1 $FASTQ_2

I checked and all the variables are defined: RGID, SM, PL, NT, DNASCOPE_MODEL, FASTA, FASTQ_1, FASTQ_2

I must be doing something stupid here, and I cannot see it....

Thanks

**Comment by DonFreed** [comment]
Which version of Sentieon are you using? Passing the model file using the `-x` argument in Sentieon bwa-mem is only supported in Sentieon version 202308 or later.

**Comment by gianfilippo** [comment]
Hi, of course :). I am using version 202112.07. Thanks

**Comment by DonFreed** [comment]
Happy to help. Updating to Sentieon 202308 or later should fix the error.
