### ISSUE TITLE
BWA error using bundle model

### ISSUE THREAD

**Issue by geocarvalho** [Sentieon/sentieon-models#7]
Hi team, I am having issues to run sentieon BWA using the bundle model:

```bash
sentieon bwa mem -R '@RG\tID:sample\tSM:sample\tPL:DNBSEQ' -t 32 ./Homo_sapiens_assembly38.fasta -x DNAscopeMGIWGS2.0.bundle/bwa.model sample_1.fq.gz sample_2.fq.gz -K 10000000 | sentieon util sort -r Homo_sapiens_assembly38.fasta -o sample.sorted.bam -t 32 --sam2bam -i - --bam_compression 1

[E::main_mem] unknown read type 'DNAscopeMGIWGS2.0.bundle/bwa.model'
```

Before running the command, should I do something with `DNAscopeMGIWGS2.0.bundle/bwa.model`?

Regards,
George.

**Comment by adm-neogenomica** [comment]
@geocarvalho  it's the version. Probably you are running with an old version of sentieon release.

**Comment by DonFreed** [comment]
Thanks @adm-neogenomica. You are correct, support for model files is only available since Sentieon 202308 and the error message is consistent with using an earlier version.
