### ISSUE TITLE
Cannot find the input model bundle file

### ISSUE THREAD

**Issue by cheninouc** [Sentieon/sentieon-models#8]
Hi @DonFreed 
Through dnascope_HiFi. Sh (https://github.com/Sentieon/sentieon-scripts/blob/master/dnascope_LongRead/dnascope_HiFi.sh) for hifi data detection SNP:
`sh dnascope_HiFi. Sh  -r ../reference/ccs/ccs.fa -i CK1_with_RG_corrected.bam  -m ./DNAscopePacBio2.1.bundle/gvcf_model -g CK1.g.vcf.gz`
The following error occurs:
Error: cannot find the input model bundle file, '/gpfshddpool/home/chenchenguang/jhspoolers/work7/DNAscopePacBio2.1.bundle/gvcf_model'

**Comment by DonFreed** [comment]
The `-m` argument needs to be set to the path of the model bundle file, without the `/gvcf_model` suffix. Here is an updated command that fixes the problem:
```sh
sh dnascope_HiFi.sh  -r ../reference/ccs/ccs.fa -i CK1_with_RG_corrected.bam  -m ./DNAscopePacBio2.1.bundle -g CK1.g.vcf.gz
```

By the way, the `dnascope_HiFi.sh` script is deprecated. I recommend running the pipeline using the [sentieon-cli](https://github.com/Sentieon/sentieon-cli) instead. You can find documentation on the new pipeline at, https://github.com/Sentieon/sentieon-cli/blob/main/docs/dnascope-longread.md
